version: '3.7'
x-common: &common
  restart: always
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"
services:
  phenix:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        PHENIX_WEB_AUTH: disabled
    command:
    - phenix
    - ui
    - --hostname-suffixes=-minimega,-phenix
    image: phenix
    container_name: phenix
    hostname: ${HOSTNAME}-phenix
    privileged: true
    <<: *common
    networks:
      phenix:
    ports:
      - 3000:3000
    volumes:
      - /dev:/dev
      - /proc:/proc
      - /etc/localtime:/etc/localtime:ro
      - /tmp/minimega:/tmp/minimega
      - /tmp/phenix:/tmp/phenix
      - /phenix:/phenix
      - /var/log/phenix:/var/log/phenix
      - /etc/phenix:/etc/phenix
    depends_on:
      - minimega
    healthcheck:
      test: phenix version
  minimega:
    image: ghcr.io/activeshadow/minimega/minimega:latest
    pull_policy: always
    container_name: minimega
    hostname: ${HOSTNAME}-minimega
    privileged: true
    cap_add:
      - ALL
    tty: true
    <<: *common
    networks:
      phenix:
        aliases:
          - ${HOSTNAME}-minimega
    ports:
      - 9000:9000/udp
      - 9001:9001
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/minimega:/tmp/minimega
      - /tmp/phenix:/tmp/phenix
      - /phenix:/phenix
    healthcheck:
      test: mm version
    environment:
      MM_FILEPATH: /phenix/images
networks:
  phenix:
